### ISSUE TITLE
Youtube video not working on production

### ISSUE THREAD

**Issue by dan89farhan** [react-page/react-page#1019]
**Describe the bug**
Hello @macrozone @PeterKottas, I hope you guys are doing well. I build the project happily and everything working great. 
I am using react router for routing. I created a blog with a youtube video block. When I redirected to the specific blog page. I am getting following error. 

loadable-components: failed to asynchronously load component 
{
    "error": "Loading chunk 7 failed.\n(missing: http://localhost/template/BlogDesigner/static/js/7.bundle.min.js)"
}

bundle.min.js:formatted:24419 ChunkLoadError: Loading chunk 7 failed.
(missing: http://localhost/template/BlogDesigner/static/js/7.bundle.min.js)
    at Function.o.e (http://localhost/template/Blogs/static/js/bundle.min.js:2:715)
    at Object.requireAsync (http://localhost/template/Blogs/static/js/bundle.min.js:2:708477)
    at n.o.resolveAsync (http://localhost/template/Blogs/static/js/bundle.min.js:2:255869)
    at n.o.loadAsync (http://localhost/template/Blogs/static/js/bundle.min.js:2:255473)
    at n.o.componentDidMount (http://localhost/template/Blogs/static/js/bundle.min.js:2:254590)
    at hl (http://localhost/template/Blogs/static/js/bundle.min.js:2:495354)
    at As (http://localhost/template/Blogs/static/js/bundle.min.js:2:512289)
    at t.unstable_runWithPriority (http://localhost/template/Blogs/static/js/bundle.min.js:2:531683)
    at Wo (http://localhost/template/Blogs/static/js/bundle.min.js:2:454041)
    at Ps (http://localhost/template/Blogs/static/js/bundle.min.js:2:509024)

I am using webpack to build the project.

I hope, you will guide me in the right direction.

this error only occurs if I am adding video block.

Note: I am deploying it on sub-domain

**Comment by macrozone** [comment]
@dan89farhan on the demo page its working as expected: https://react-page.github.io/

that seems more of a setup/webpack problem as it can't lazy load a certain bundle.

React page uses dynamic imports to lazily load data that is not used everytime (e.g. the editor ui).

Your stack trace shows that it tries to fetch data from http://localhost, but it can't access that. 

The title says that it does not work on "production", so i guess that you bundled it somehow and then run it somewhere, but that it tries to load data from localhost (which does not look like production).


Its not a problem with react-page, but with your setup and you should probably ask in a webpack community about that.

My personal recommendation is to use a react-framework like nextjs, gatsby or create-react-app as they support developing and deploying an application properly.

**Comment by dan89farhan** [comment]
@macrozone, Thank you for your reply.

Yes, My webpack config was wrong. 

publicPath: ''/template/BlogDesigner/"
Correct path : 
publicPath: ''/template/Blogs/"

So I am closing this issue
