### ISSUE TITLE
Fresh fork, and then 'yarn dev' throws errors

### ISSUE THREAD

**Issue by zehawki** [react-page/react-page#1177]
**Describe the bug**
After `yarn dev`:

```
@react-page/plugins-html5-video: src/createPlugin.tsx(1,33): error TS2307: Cannot find module '@react-page/editor' or it
s corresponding type declarations.
@react-page/plugins-html5-video: src/default/settings.tsx(3,26): error TS2307: Cannot find module '@react-page/editor' o
r its corresponding type declarations.
@react-page/plugins-html5-video: src/Renderer/Html5VideoHtmlRenderer.tsx(1,47): error TS2307: Cannot find module '@react
-page/editor' or its corresponding type declarations.
@react-page/plugins-html5-video: src/types/settings.ts(1,47): error TS2307: Cannot find module '@react-page/editor' or i
ts corresponding type declarations.
@react-page/plugins-image: src/Controls/ImageControls.tsx(5,46): error TS2307: Cannot find module '@react-page/editor' o
r its corresponding type declarations.
@react-page/plugins-image: src/createPlugin.tsx(1,33): error TS2307: Cannot find module '@react-page/editor' or its corr
esponding type declarations.
@react-page/plugins-image: src/default/settings.tsx(3,26): error TS2307: Cannot find module '@react-page/editor' or its
corresponding type declarations.
@react-page/plugins-image: src/index.tsx(1,33): error TS2307: Cannot find module '@react-page/editor' or its correspondi
ng type declarations.
@react-page/plugins-image: src/index.tsx(2,43): error TS2307: Cannot find module '@react-page/editor' or its correspondi
ng type declarations.
@react-page/plugins-image: src/Renderer/ImageHtmlRenderer.tsx(4,47): error TS2307: Cannot find module '@react-page/edito
r' or its corresponding type declarations.
@react-page/plugins-image: src/Renderer/ImageHtmlRenderer.tsx(5,26): error TS2307: Cannot find module '@react-page/edito
r' or its corresponding type declarations.
@react-page/plugins-image: src/types/controls.ts(4,8): error TS2307: Cannot find module '@react-page/editor' or its corr
esponding type declarations.
@react-page/plugins-image: src/types/settings.ts(1,58): error TS2307: Cannot find module '@react-page/editor' or its cor
responding type declarations.
@react-page/plugins-html5-video: error Command failed with exit code 2.
@react-page/plugins-html5-video: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-background: src/Controls/Controls.tsx(5,44): error TS2307: Cannot find module '@react-page/editor' o
r its corresponding type declarations.
@react-page/plugins-background: src/Controls/sub/Color.tsx(2,31): error TS2307: Cannot find module '@react-page/editor'
or its corresponding type declarations.
@react-page/plugins-background: src/Controls/sub/Color.tsx(3,29): error TS2307: Cannot find module '@react-page/editor'
or its corresponding type declarations.
@react-page/plugins-background: src/Controls/sub/Image.tsx(5,49): error TS2307: Cannot find module '@react-page/editor'
or its corresponding type declarations.
@react-page/plugins-background: src/Controls/sub/Image.tsx(6,29): error TS2307: Cannot find module '@react-page/editor'
or its corresponding type declarations.
@react-page/plugins-background: src/Controls/sub/LinearGradient.tsx(6,31): error TS2307: Cannot find module '@react-page
/editor' or its corresponding type declarations.
@react-page/plugins-background: src/Controls/sub/LinearGradient.tsx(7,29): error TS2307: Cannot find module '@react-page
/editor' or its corresponding type declarations.
@react-page/plugins-background: src/createPlugin.tsx(7,33): error TS2307: Cannot find module '@react-page/editor' or its
 corresponding type declarations.
@react-page/plugins-background: src/createPlugin.tsx(8,26): error TS2307: Cannot find module '@react-page/editor' or its
 corresponding type declarations.
@react-page/plugins-background: src/index.tsx(9,26): error TS2307: Cannot find module '@react-page/editor' or its corres
ponding type declarations.
@react-page/plugins-background: src/Renderer/BackgroundHtmlRenderer.tsx(1,31): error TS2307: Cannot find module '@react-
page/editor' or its corresponding type declarations.
@react-page/plugins-background: src/types/api.ts(3,44): error TS2307: Cannot find module '@react-page/editor' or its cor
responding type declarations.
@react-page/plugins-background: src/types/component.ts(1,47): error TS2307: Cannot find module '@react-page/editor' or i
ts corresponding type declarations.
@react-page/plugins-background: src/types/gradient.ts(1,31): error TS2307: Cannot find module '@react-page/editor' or it
s corresponding type declarations.
@react-page/plugins-background: src/types/renderer.ts(2,44): error TS2307: Cannot find module '@react-page/editor' or it
s corresponding type declarations.
@react-page/plugins-background: src/types/settings.ts(1,60): error TS2307: Cannot find module '@react-page/editor' or it
s corresponding type declarations.
@react-page/plugins-background: src/types/state.ts(1,31): error TS2307: Cannot find module '@react-page/editor' or its c
orresponding type declarations.
@react-page/plugins-image: error Command failed with exit code 2.
@react-page/plugins-image: error Command failed with exit code 2.
@react-page/plugins-image: ERROR: "build:lib:watch" exited with 2.
@react-page/plugins-image: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-image: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-html5-video: error Command failed with exit code 2.
@react-page/plugins-html5-video: ERROR: "build:lib:watch" exited with 2.
@react-page/plugins-html5-video: error Command failed with exit code 1.
@react-page/plugins-html5-video: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-html5-video: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-background: error Command failed with exit code 2.
@react-page/plugins-background: error Command failed with exit code 2.
@react-page/plugins-background: ERROR: "build:lib:watch" exited with 2.
@react-page/plugins-divider: src/createPlugin.tsx(1,33): error TS2307: Cannot find module '@react-page/editor' or its co
rresponding type declarations.
@react-page/plugins-divider: src/createPlugin.tsx(2,26): error TS2307: Cannot find module '@react-page/editor' or its co
rresponding type declarations.
@react-page/plugins-divider: src/types/settings.ts(1,47): error TS2307: Cannot find module '@react-page/editor' or its c
orresponding type declarations.
@react-page/plugins-divider: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-background: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-background: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-background: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-image: error Command failed with exit code 1.
@react-page/plugins-image: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-divider: error Command failed with exit code 2.
@react-page/plugins-divider: error Command failed with exit code 2.
@react-page/plugins-divider: ERROR: "build:lib:watch" exited with 2.
lerna ERR! yarn run build:watch exited 1 in '@react-page/plugins-html5-video'
lerna ERR! yarn run build:watch stdout:
```

**To Reproduce**
1. Freshly fork react-page
2. Clone into local
3. Steps as per https://react-page.github.io/docs/#/CONTRIBUTING

**Comment by macrozone** [comment]
@zehawki can you do a `yarn install` and then `yarn build` ? lerna setup is still a bit annoying, maybe i can update that in the future...

**Comment by zehawki** [comment]
Hah perfect. Working fine, thanks.

**Comment by zehawki** [comment]
Hah perfect. Working fine, thanks.

**Comment by zehawki** [comment]
Yarn install and yarn build was fine. Then upon yarn dev, I get a different error.

To cross check, I did a fresh clone of this repo (not the fork). Then in order executed - `yarn`, `yarn bootstrap`, `yarn install`, `yarn build`, `yarn dev` which gives the same error as in the forked:

```
@react-page/examples: Error: Cannot find module '@react-page/editor/lib/index.css'
@react-page/examples:     at webpackMissingModule (webpack-internal:///./pages/_app.tsx:9:50)
@react-page/examples:     at eval (webpack-internal:///./pages/_app.tsx:9:157)
@react-page/examples:     at Object../pages/_app.tsx (C:\Data\Work\react-page\examples\.next\server\pages\_app.js:22:1)
@react-page/examples:     at __webpack_require__ (C:\Data\Work\react-page\examples\.next\server\webpack-runtime.js:33:42)
@react-page/examples:     at __webpack_exec__ (C:\Data\Work\react-page\examples\.next\server\pages\_app.js:64:39)
@react-page/examples:     at C:\Data\Work\react-page\examples\.next\server\pages\_app.js:65:28
@react-page/examples:     at Object.<anonymous> (C:\Data\Work\react-page\examples\.next\server\pages\_app.js:68:3)
@react-page/examples:     at Module._compile (node:internal/modules/cjs/loader:1103:14)
@react-page/examples:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
@react-page/examples:     at Module.load (node:internal/modules/cjs/loader:981:32) {
@react-page/examples:   code: 'MODULE_NOT_FOUND'
@react-page/examples: }
```

**Comment by macrozone** [comment]
@zehawki i just did a fresh checkout and run `yarn install && yarn build && yarn dev` which works.

maybe you have problem with windows? I am afraid I cannot help with windows.

**Comment by yaizudamashii** [comment]
@macrozone Just worked with the command you posted, `yarn install && yarn build && yarn dev` but the repo does not work at all with npm commands!  I think updating the documentation will help many people.

**Comment by macrozone** [comment]
> @macrozone Just worked with the command you posted, `yarn install && yarn build && yarn dev` but the repo does not work at all with npm commands! I think updating the documentation will help many people.

contributing guidelines are here https://github.com/react-page/react-page/blob/master/CONTRIBUTING.md and it shows the commands. 

if you just want to use the npm package, you can of course use npm

**Comment by zehawki** [comment]
This is certainly not working. Tried in Ubuntu. Here are the commands:

```
git clone https://github.com/react-page/react-page.git
cd react-page
yarn install
yarn build
yarn dev
```

Yarn dev throws error:

```
yarn run v1.22.10
$ cross-env TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling npm-run-all -p build:watch dev:examples
$ cross-env NODE_ENV=development lerna run dev --stream
$ cross-env NODE_ENV=development lerna run build:watch --parallel
lerna notice cli v3.22.1
lerna notice cli v3.22.1
lerna info Executing command in 9 packages: "yarn run build:watch"
lerna info Executing command in 1 package: "yarn run dev"
@react-page/examples: $ next dev
@react-page/editor: $ npm-run-all --parallel build:lib:watch build:css:watch
@react-page/plugins-slate: $ npm-run-all --parallel build:lib:watch build:css:watch
@react-page/plugins-divider: $ npm-run-all --parallel build:lib:watch build:css:watch
@react-page/plugins-spacer: $ npm-run-all --parallel build:lib:watch build:css:watch
@react-page/plugins-background: $ npm-run-all --parallel build:lib:watch build:css:watch
@react-page/plugins-video: $ npm-run-all --parallel build:lib:watch build:css:watch
@react-page/react-admin: $ npm-run-all --parallel build:lib:watch
@react-page/plugins-image: $ npm-run-all --parallel build:lib:watch build:css:watch
@react-page/plugins-html5-video: $ npm-run-all --parallel build:lib:watch build:css:watch
@react-page/examples: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
@react-page/editor: $ yarn build:lib -- --watch
@react-page/editor: $ npm-run-all build:css -- -w
@react-page/plugins-background: $ yarn build:lib -- --watch
@react-page/plugins-spacer: $ npm-run-all build:css -- -w
@react-page/plugins-slate: $ npm-run-all build:css -- -w
@react-page/plugins-image: $ yarn build:lib -- --watch
@react-page/plugins-divider: $ npm-run-all build:css -- -w
@react-page/plugins-slate: $ yarn build:lib -- --watch
@react-page/plugins-background: $ npm-run-all build:css -- -w
@react-page/plugins-video: $ npm-run-all build:css -- -w
@react-page/plugins-spacer: $ yarn build:lib -- --watch
@react-page/react-admin: $ yarn build:lib -- --watch
@react-page/plugins-html5-video: $ yarn build:lib -- --watch
@react-page/plugins-html5-video: $ npm-run-all build:css -- -w
@react-page/plugins-divider: $ yarn build:lib -- --watch
@react-page/plugins-video: $ yarn build:lib -- --watch
@react-page/plugins-image: $ npm-run-all build:css -- -w
@react-page/editor: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
@react-page/editor: $ tsc -p ./tsconfig.json && tsc -p ./tsconfig-es.json --watch
@react-page/plugins-background: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
@react-page/plugins-background: $ tsc -p ./tsconfig.json && tsc -p ./tsconfig-es.json --watch
@react-page/plugins-slate: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
@react-page/plugins-slate: $ tsc -p ./tsconfig.json && tsc -p ./tsconfig-es.json --watch
@react-page/plugins-image: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
@react-page/plugins-html5-video: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
@react-page/plugins-image: $ tsc -p ./tsconfig.json && tsc -p ./tsconfig-es.json --watch
@react-page/plugins-html5-video: $ tsc -p ./tsconfig.json && tsc -p ./tsconfig-es.json --watch
@react-page/react-admin: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
@react-page/react-admin: $ tsc -p ./tsconfig.json && tsc -p ./tsconfig-es.json --watch
@react-page/plugins-video: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
@react-page/plugins-video: $ tsc -p ./tsconfig.json && tsc -p ./tsconfig-es.json --watch
@react-page/plugins-spacer: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
@react-page/plugins-spacer: $ tsc -p ./tsconfig.json && tsc -p ./tsconfig-es.json --watch
@react-page/plugins-divider: warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
@react-page/examples: Killed
@react-page/plugins-divider: $ tsc -p ./tsconfig.json && tsc -p ./tsconfig-es.json --watch
@react-page/editor: $ postcss --config ../../config/postcss.config.js --dir lib/ src/index.css
@react-page/plugins-spacer: $ postcss --config ../../../../config/postcss.config.js --dir lib/ src/index.css
@react-page/plugins-image: $ postcss --config ../../../../config/postcss.config.js --dir lib/ src/index.css
@react-page/plugins-html5-video: $ postcss --config ../../../../config/postcss.config.js --dir lib/ src/index.css
@react-page/plugins-slate: $ postcss --config ../../../../config/postcss.config.js --dir lib/ src/index.css
@react-page/plugins-divider: $ postcss --config ../../../../config/postcss.config.js --dir lib/ src/index.css
@react-page/plugins-background: $ postcss --config ../../../../config/postcss.config.js --dir lib/ src/index.css
@react-page/plugins-video: $ postcss --config ../../../../config/postcss.config.js --dir lib/ src/index.css
@react-page/examples: error Command failed with exit code 137.
@react-page/examples: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run dev exited 137 in '@react-page/examples'
@react-page/plugins-divider: Killed
@react-page/plugins-divider: error Command failed with exit code 137.
@react-page/plugins-divider: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@react-page/plugins-divider: error Command failed with exit code 137.
@react-page/plugins-divider: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "dev:examples" exited with 137.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by macrozone** [comment]
@zehawki I looked up what exit code 137 means on google and it seems a process ran out of memory. This seems to be a problem on your local machine. Do you work in a vm?

**Comment by zehawki** [comment]
@macrozone thank you! I increased the VM memory from 4 to 8GB, and its fine now. (Its a bit embarrassing - I should have checked 137 myself).
