### ISSUE TITLE
jsx-runtime not exported (DndProvider error)

### ISSUE THREAD

**Issue by Picard-Raphael** [react-page/react-page#1190]
Hi,
I want to try reactpage but when npm run dev, i have error :

```
error - ./node_modules/react-dnd/dist/esm/core/DndProvider.mjs:28:0
Module not found: Package path ./jsx-runtime.js is not exported from package /home/raphael/Documents/nextjs/rnd-text-editor-nextjs/node_modules/react (see exports field in /home/raphael/Documents/nextjs/rnd-text-editor-nextjs/node_modules/react/package.json)
```

![image](https://user-images.githubusercontent.com/95343603/168995318-22787a73-a6fb-4d40-ab82-1c8023270f93.png)

I use : boilerplate nextjs + typescript
package.json :
![image](https://user-images.githubusercontent.com/95343603/168997418-190ffb74-497b-4dc8-9742-8d69ee88f534.png)

index.tsx :
![image](https://user-images.githubusercontent.com/95343603/168998140-1d639dda-b8b6-408f-ab34-9deecc03e437.png)

**Comment by macrozone** [comment]
please use react 17 at the moment.

see also https://github.com/react-dnd/react-dnd/issues/3416

**Comment by hmbrg** [comment]
I'm still running into this error with React 18 and Next.js 13. Any timeline on when this is gonna be fixed? The referenced issue above with react-dnd seems to have been solved.

**Comment by macrozone** [comment]
@hmbrg i just tried to update next to 13 and have no problem.

can you share your package.json?

**Comment by macrozone** [comment]
can confirm, happens now with next 13.

i am not sure why that happens though as we also ship esm.

@hmbrg did you try to apply the workaround with transpile-modules?

**Comment by hmbrg** [comment]
Thanks for looking into this!

I've tried the solution provided in the react-dnd issue referenced above here: https://github.com/react-dnd/react-dnd/issues/3416#issuecomment-1126159287

This lead to getting this error: 
```
error - ./node_modules/@react-page/editor/lib/core/Provider/DndProvider.js:7:18
Module not found: ESM packages (react-dnd) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

Import trace for requested module:
./node_modules/@react-page/editor/lib/core/Provider/index.js
./node_modules/@react-page/editor/lib/editor/EditableEditor.js
./node_modules/@react-page/editor/lib/editor/Editor.js
./node_modules/@react-page/editor/lib/index.js
./components/cms/editor/Editor.tsx
./pages/cms/dev/fancy-editor.tsx
```

Seems like react-page has to be rebuilt using the updated packages and maybe even change its build process, because of react-dnd using ESM modules, if I'm not mistaken.

I would be happy to look into this, but I might need some guidance in case updating the build process is needed.

**Comment by macrozone** [comment]
@hmbrg i am also toying around with it right now.

the problem is the whole commonjs-to-esm transition which is very confusing

we actually shipped esm long ago, because otherwise code splitting would not work, i am still surprised that it now seems falls back to use the common-js version

**Comment by macrozone** [comment]
@hmbrg do you test it in this repo? or in your own?

**Comment by hmbrg** [comment]
Just in my own repo so far. Are you not able to reproduce this error?

**Comment by macrozone** [comment]
@hmbrg yes, but i cannot fix it at the moment. I recommend to stick with next 12 until this is fixed

**Comment by hmbrg** [comment]
I have been looking into this again, sadly with no luck so far. 
Sorry to be so pushy, but do you have any timeframe on when this is going to be fixed?

**Comment by macrozone** [comment]
@hmbrg checking the upstream issue right now

**Comment by macrozone** [comment]
@hmbrg at least the example project works with next13 without any problem, did you try to use the lastest nextjs version? (13.1.2)

**Comment by 634750802** [comment]
hi @macrozone
I'm using next 13.1.2 now, and I have met a bug but I don't know if it was from react 18

some input in dialog is not working, I can't type anything:

![image](https://user-images.githubusercontent.com/12960671/214209770-07f2a815-7a3d-42d5-8db5-f6fbc8c022a2.png)

In this one, I can input title but not href, or check the checkbox
![image](https://user-images.githubusercontent.com/12960671/214209951-be21a891-ecfa-4b61-9b7f-26daf7c6f828.png)

warning was reported in console
```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
...
    at Dialog (webpack-internal:///../node_modules/.pnpm/@mui+material@5.11.5_lskpmcsdi7ipu6qpuapyu56ihm/node_modules/@mui/material/Dialog/Dialog.js:173:83)
    at Controls (webpack-internal:///../node_modules/.pnpm/@react-page+plugins-slate@5.3.0_leemgkc4evhvet5nzohlsulcqm/node_modules/@react-page/plugins-slate/lib-es/pluginFactories/components/UniformsControls.js:34:32)
    at PluginControls (webpack-internal:///../node_modules/.pnpm/@react-page+plugins-slate@5.3.0_leemgkc4evhvet5nzohlsulcqm/node_modules/@react-page/plugins-slate/lib-es/components/PluginControls.js:50:24)
    at PluginButton (webpack-internal:///../node_modules/.pnpm/@react-page+plugins-slate@5.3.0_leemgkc4evhvet5nzohlsulcqm/node_modules/@react-page/plugins-slate/lib-es/components/PluginButton.js:52:24)
    at div
    at Controls (webpack-internal:///../node_modules/.pnpm/@react-page+plugins-slate@5.3.0_leemgkc4evhvet5nzohlsulcqm/node_modules/@react-page/plugins-slate/lib-es/components/Controls.js:10:25)
...
```

**Comment by macrozone** [comment]
@634750802 can you list your package.json? (and the used versions from your lock-file?)

the bug does not occure with react 18 and next 13.1.2 on the [demo](https://react-page.github.io/) , but i had this problem before

**Comment by 634750802** [comment]
@macrozone i have just created a demo [repo](https://github.com/634750802/react-page-example) and a preview on [codespace](https://634750802-didactic-computing-machine-7v7qxvqv6553rgrx-3000.preview.app.github.dev/), the issue was reproduced.

**Comment by 634750802** [comment]
hi, @macrozone, should I create a new issue for it?

**Comment by macrozone** [comment]
> hi, @macrozone, should I create a new issue for it?

no, sorry for the delayy, will check out your example

**Comment by macrozone** [comment]
> @macrozone i have just created a demo [repo](https://github.com/634750802/react-page-example) and a preview on [codespace](https://634750802-didactic-computing-machine-7v7qxvqv6553rgrx-3000.preview.app.github.dev/), the issue was reproduced.
> 
> my local node is v18.12.1, npm is 8.19.2

hey, i checked it out, installed it (with yarn) and had no problem. maybe its npm related?

**Comment by macrozone** [comment]
@634750802 hi, i found the problem, https://github.com/react-page/react-page/issues/1281

**Comment by andreastoermer** [comment]
Hallo,

ich habe mir erst heute mal wieder den react-page Editor in der Version 5.4.4 eingerichtet. Nutze in der app React 18 (und Vite als Builder).

Bekomme derzeit die folgende Fehlermeldung:

` [ERROR] Missing "./jsx-runtime.js" specifier in "react" package [plugin vite:dep-pre-bundle]

    node_modules/react-dnd/dist/esm/core/DndProvider.mjs:28:28:
      28 │ import { jsx as _jsx } from "react/jsx-runtime.js";
         ╵                             ~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23671:19)
    at handlePlugins (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:776:5)
    at /Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2172:68
    at new Promise (<anonymous>)
    at Object.context (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2172:27)
    at Object.context (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2012:58)
    at prepareEsbuildOptimizerRun (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:44414:35)

/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/react-dnd/dist/esm/core/DndProvider.mjs:28:28: ERROR: [plugin: vite:dep-pre-bundle] Missing "./jsx-runtime.js" specifier in "react" package
    at failureErrorWithLog (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1048:25
    at /Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: Error: Missing "./jsx-runtime.js" specifier in "react" package
          at e (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:25)
          at n (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:627)
          at o (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:1297)
          at resolveExportsOrImports (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23407:20)
          at resolveDeepImport (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23426:31)
          at tryNodeResolve (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23115:20)
          at Context.resolveId (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:22876:28)
          at Object.resolveId (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42811:46)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:64074:21,
      id: '',
      location: {
        column: 28,
        file: 'node_modules/react-dnd/dist/esm/core/DndProvider.mjs',
        length: 22,
        line: 28,
        lineText: 'import { jsx as _jsx } from "react/jsx-runtime.js";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 20,
            file: 'node_modules/esbuild/lib/main.js',
            length: 0,
            line: 1279,
            lineText: '      let promise = setup({\n' +
              '    at setup (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23671:19)\n' +
              '    at handlePlugins (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1279:21)\n' +
              '    at buildOrContextImpl (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:968:5)\n' +
              '    at Object.buildOrContext (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:776:5)\n' +
              '    at /Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2172:68\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at Object.context (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2172:27)\n' +
              '    at Object.context (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2012:58)\n' +
              '    at prepareEsbuildOptimizerRun (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:44414:35)',
            namespace: 'file',
            suggestion: ''
          },
          text: 'This error came from the "onResolve" callback registered here:'
        }
      ],
      pluginName: 'vite:dep-pre-bundle',
      text: 'Missing "./jsx-runtime.js" specifier in "react" package'
    }
  ],
  warnings: []
}
`

Since nothing has been written here for some time, does anyone have an update on the compatibility between react-page and React 18?

Thanks in advance.

**Comment by macrozone** [comment]
> Hello,
> 
> I just set up the react-page editor again today in version 5.4.4. Am using React 18 in the app (and Vite as builder).
> 
> Currently getting the following error message:
> 
> ```
> [ERROR] Missing "./jsx-runtime.js" specifier in "react" package [plugin vite:dep-pre-bundle]
> 
>     node_modules/react-dnd/dist/esm/core/DndProvider.mjs:28:28:
>       28 │ import { jsx as _jsx } from "react/jsx-runtime.js";
>          ╵                             ~~~~~~~~~~~~~~~~~~~~~~
> 
>   This error came from the "onResolve" callback registered here:
> 
>     node_modules/esbuild/lib/main.js:1279:20:
>       1279 │       let promise = setup({
>            ╵                     ^
> 
>     at setup (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23671:19)
>     at handlePlugins (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1279:21)
>     at buildOrContextImpl (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:968:5)
>     at Object.buildOrContext (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:776:5)
>     at /Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2172:68
>     at new Promise (<anonymous>)
>     at Object.context (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2172:27)
>     at Object.context (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2012:58)
>     at prepareEsbuildOptimizerRun (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:44414:35)
> 
> /Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1636
>   let error = new Error(`${text}${summary}`);
>               ^
> 
> Error: Build failed with 1 error:
> node_modules/react-dnd/dist/esm/core/DndProvider.mjs:28:28: ERROR: [plugin: vite:dep-pre-bundle] Missing "./jsx-runtime.js" specifier in "react" package
>     at failureErrorWithLog (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1636:15)
>     at /Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1048:25
>     at /Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1512:9
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   errors: [
>     {
>       detail: Error: Missing "./jsx-runtime.js" specifier in "react" package
>           at e (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:25)
>           at n (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:627)
>           at o (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:1297)
>           at resolveExportsOrImports (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23407:20)
>           at resolveDeepImport (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23426:31)
>           at tryNodeResolve (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23115:20)
>           at Context.resolveId (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:22876:28)
>           at Object.resolveId (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42811:46)
>           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>           at async file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:64074:21,
>       id: '',
>       location: {
>         column: 28,
>         file: 'node_modules/react-dnd/dist/esm/core/DndProvider.mjs',
>         length: 22,
>         line: 28,
>         lineText: 'import { jsx as _jsx } from "react/jsx-runtime.js";',
>         namespace: '',
>         suggestion: ''
>       },
>       notes: [
>         {
>           location: {
>             column: 20,
>             file: 'node_modules/esbuild/lib/main.js',
>             length: 0,
>             line: 1279,
>             lineText: '      let promise = setup({\n' +
>               '    at setup (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23671:19)\n' +
>               '    at handlePlugins (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:1279:21)\n' +
>               '    at buildOrContextImpl (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:968:5)\n' +
>               '    at Object.buildOrContext (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:776:5)\n' +
>               '    at /Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2172:68\n' +
>               '    at new Promise (<anonymous>)\n' +
>               '    at Object.context (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2172:27)\n' +
>               '    at Object.context (/Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/esbuild/lib/main.js:2012:58)\n' +
>               '    at prepareEsbuildOptimizerRun (file:///Users/andreastormer/Documents/sandboxer-tec/projects/intranet/code/frontend/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:44414:35)',
>             namespace: 'file',
>             suggestion: ''
>           },
>           text: 'This error came from the "onResolve" callback registered here:'
>         }
>       ],
>       pluginName: 'vite:dep-pre-bundle',
>       text: 'Missing "./jsx-runtime.js" specifier in "react" package'
>     }
>   ],
>   warnings: []
> }
> ```
> 
> Since nothing has been written here for some time, does anyone have an update on the compatibility between react-page and React 18?
> 
> Thanks in advance.

Hi,

React 18 works, the problem is vite.

Since i personally don't use vite (i think nextjs is the more obvious choice for typical content-heavy apps), its a bit hard for me to debug this.

as suggested here https://github.com/react-page/react-page/issues/1267#issuecomment-1491537110 it would be cool if someone could contribute a vite example in the project in a pull request where we can test the build problems. This helps to fix problems related to bundling. 

I also know that there was some activity within react-dnd.

**Comment by andreastoermer** [comment]
https://github.com/andreastoermer/vite-reactpage-example

Here is an example with a Vite Config. When I start this I get exactly the error I currently have. Feel free to test with it, it is set to public.

I want to use react page in an intranet application that has been under development for over a year. And since SSR was not needed, we decided to use Vite as a base (we didn't want to use create-react-app anymore).

**Comment by hmbrg** [comment]
> @hmbrg at least the example project works with next13 without any problem (only some hydration errors), did you try to use the lastest nextjs version? (13.1.2)

Sorry for the late response. Updating to 13.1.2 fixed the issue momentarily, but we since upgraded to next 13.4.5 and the issue reappeared, but I've since been able to fix the issue.

To fix use react-dnd with ESM support we need to upgrade the version react-page is using internally to ^16. In our pnpm repo, this can be achieved by adding the following to the package.json:
```
 "pnpm": {
    "overrides": {
      "react-dnd": "^16.0.0"
    },
}
```

We then get the following error when trying to build using Next:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/react-dnd/dist/index.js from /node_modules/@react-page/editor/lib/core/components/hooks/nodeActions.js not supported.
Instead change the require of index.js in /node_modules/@react-page/editor/lib/core/components/hooks/nodeActions.js to a dynamic import() which is available in all CommonJS modules.
```

This means we need to update all imports in the react-page package to use `import()` instead of `require()`. To do this with pnpm. We can use the patch command like this: `pnpm patch @react-page/editor`.  Open the folder and use the search & replace functionality of your IDE to change all imports of react-dnd like this: 
<img width="420" alt="CleanShot 2023-06-15 at 05 14 58@2x" src="https://github.com/react-page/react-page/assets/7304269/529d04f7-2f06-4cb6-9e46-f37f13a11fe2">

After that run `pnpm patch-commit <PATCH_FOLDER>` to apply the patch.

I hope this is helpful for people using Next.js! 
If this a generally appliable patch for all bundlers, I would be happy to create a PR to finally fix this, but I'm not sure if this just works for Next.js.

**Comment by macrozone** [comment]
hey @hmbrg thanks for the info.

will have a look if we can fix this

**Comment by neutron92** [comment]
Some probleme 
```
 "dependencies": {
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@react-page/editor": "^5.4.4",
    "@react-page/plugins-image": "^5.4.4",
    "@react-page/plugins-slate": "^5.4.4",
    "@types/node": "20.4.0",
    "@types/react": "18.2.14",
    "@types/react-dom": "18.2.6",
    "autoprefixer": "10.4.14",
    "eslint": "8.44.0",
    "eslint-config-next": "13.4.8",
    "jsx-runtime": "^1.2.0",
    "next": "13.4.8",
    "react": "18.2.0",
    "react-dom": "18.2.0",
  }

```
<img width="1479" alt="image" src="https://github.com/react-page/react-page/assets/6135555/04657fa8-e691-4ba0-9a55-b84e8d10eabd">

**Comment by IN2TEC** [comment]
Hey guys, first of all, I would like to say thank you for this awesome component you have created. Unfortunately, we are on Mui 5 and REACT 18, but we would like to make it work. Does anyone know when to expect the next release or can someone help with fixing the existing package so we can use it?!?!?!?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Happening to us too, will this be fixed?

**Comment by grwgreg** [comment]
> @hmbrg
> This fix just worked for me on next 14.0.3 (react 18.2).

I spoke too soon. The slate plugin works for the most part but the href text input doesn't update onkeypress. Same issue with @react-page/plugins-video, the text input for the video URL is broken. Surprisingly the image plugin works fine.

**Comment by macrozone** [comment]
> Hey guys, first of all, I would like to say thank you for this awesome component you have created. Unfortunately, we are on Mui 5 and REACT 18, but we would like to make it work. Does anyone know when to expect the next release or can someone help with fixing the existing package so we can use it?!?!?!?

mui 5 and react 18 do work, in fact the example project is using that. I also have a production app that is using those version

**Comment by macrozone** [comment]
> > @hmbrg
> > This fix just worked for me on next 14.0.3 (react 18.2).
> 
> I spoke too soon. The slate plugin works for the most part but the href text input doesn't update onkeypress. Same issue with @react-page/plugins-video, the text input for the video URL is broken. Surprisingly the image plugin works fine.

is this a new issue with next 14?

**Comment by loordbeerus** [comment]
hi 
I'm using react 18 and i got this error 
Module not found: Error: Package path ./jsx-runtime.js is not exported from package C:\Users\Aymen\Documents\work\mike\questionner-v3\node_modules\react (see exports field in C:\Users\Aymen\Documents\work\mike\questionner-v3\node_modules\react\package.json)

**Comment by pinkasey** [comment]
I came across a similar problem -
I'm using `react-scripts` with react 18, and I installed `react-page` v5.4.5. not using next.js.
Since I'm using it in conjuction with Decap CMS, I wanted it packaged separately from my site, under `public/admin`.
Claude helped me create a `webpack` config file for it, but it failed with the error 
```
ERROR in ./node_modules/@react-page/editor/node_modules/react-dnd/dist/esm/core/DndProvider.mjs 28:0-51
Module not found: Error: Package path ./jsx-runtime.js is not exported from package ...
```
**The problem is that they removed the `.js` in react v18.**

The solution - 
add alias to the webpack config:
```
    resolve: {
        extensions: ['.js', '.jsx', '.mjs'],
        alias: {
            "react/jsx-runtime.js": "react/jsx-runtime",
            "react/jsx-dev-runtime.js": "react/jsx-dev-runtime",
        },
    },
```

My complete webpack config, for decap + react-page:
```
const path = require('path');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
    entry: './src/admin/index.js',
    mode: 'development',
    output: {
        path: path.resolve(__dirname, 'build/admin'),
        filename: 'bundle.js',
    },
    resolve: {
        extensions: ['.js', '.jsx', '.mjs'],
        alias: {
            "react/jsx-runtime.js": "react/jsx-runtime",
            "react/jsx-dev-runtime.js": "react/jsx-dev-runtime",
        },
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx|mjs)$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env', '@babel/preset-react']
                    }
                }
            },
        ],
    },
    plugins: [
        new CopyPlugin({
            patterns: [
                { from: 'public/admin/index.html', to: 'index.html' },
                { from: 'public/admin/config.yml', to: 'config.yml' },
            ]
        })
    ]
};
```

**Comment by pinkasey** [comment]
Why not fix this... 😒
See my last comment
