### ISSUE TITLE
Maximum update depth exceeded error

### ISSUE THREAD

**Issue by zwk5004** [react-page/react-page#888]
**Version:** 1.0.0-beta.14

**Description:** When loading an object from the backend and changing the editor value, it creates this error.  Removing the editor allows the page to load normal, eliminating cause coming from anything outside the Editor component.   I have provided the component that the Editor is in.  Not sure if I have something wrong or if it's a bug in the 1.0.0 version.

**Component:**
```const cellPlugins = [slate(), image];

type PageEditorProps = {
  name: string;
  editorValue: Value;
  setEditorValue: (value: Value) => void;
};

export const PageEditor = ({
  editorValue,
  setEditorValue
}: PageEditorProps): ReactElement => {
  return (
    <div style={{ color: "white", paddingBottom: 10 }}>
      <Editor
        cellPlugins={cellPlugins}
        value={editorValue}
        onChange={setEditorValue}
      />
    </div>
  );
};
```
**Error:**
```
index.js:1 The above error occurred in the <ForwardRef(InputBase)> component:
at InputBase (http://localhost:3000/static/js/7.chunk.js:18959:30)
    at WithStyles(ForwardRef(InputBase)) (http://localhost:3000/static/js/7.chunk.js:43647:31)
    at Input (http://localhost:3000/static/js/7.chunk.js:18364:32)
    at WithStyles(ForwardRef(Input)) (http://localhost:3000/static/js/7.chunk.js:43647:31)
    at div
    at FormControl (http://localhost:3000/static/js/7.chunk.js:15009:24)
    at WithStyles(ForwardRef(FormControl)) (http://localhost:3000/static/js/7.chunk.js:43647:31)
    at TextField (http://localhost:3000/static/js/7.chunk.js:34759:28)
    at WithStyles(ForwardRef(TextField)) (http://localhost:3000/static/js/7.chunk.js:43647:31)
    at div
    at div
    at div
    at ContentEditorContainer (http://localhost:3000/static/js/main.chunk.js:2618:3)
    at Connect(ContentEditorContainer) (http://localhost:3000/static/js/7.chunk.js:123938:75)
    at Route (http://localhost:3000/static/js/7.chunk.js:126837:29)
    at Switch (http://localhost:3000/static/js/7.chunk.js:127039:29)
    at main
    at div
    at AdminContainer (http://localhost:3000/static/js/main.chunk.js:2084:3)
    at Route (http://localhost:3000/static/js/7.chunk.js:126837:29)
    at Switch (http://localhost:3000/static/js/7.chunk.js:127039:29)
    at div
    at Body (http://localhost:3000/static/js/main.chunk.js:3354:18)
    at div
    at Router (http://localhost:3000/static/js/7.chunk.js:126472:30)
    at App
    at ThemeProvider (http://localhost:3000/static/js/7.chunk.js:42351:24)
    at Provider (http://localhost:3000/static/js/7.chunk.js:123651:20)
    at Auth0Provider (http://localhost:3000/static/js/7.chunk.js:3956:23)

Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:23803)
    at scheduleUpdateOnFiber (react-dom.development.js:21835)
    at dispatchAction (react-dom.development.js:16139)
    at InputBase.js:427
    at invokePassiveEffectCreate (react-dom.development.js:23487)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at flushPassiveEffectsImpl (react-dom.development.js:23574)
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushPassiveEffects (react-dom.development.js:23447)
    at performSyncWorkOnRoot (react-dom.development.js:22269)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at batchedEventUpdates$1 (react-dom.development.js:22403)
    at batchedEventUpdates (react-dom.development.js:3745)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507)
    at attemptToDispatchEvent (react-dom.development.js:6005)
    at dispatchEvent (react-dom.development.js:5924)
checkForNestedUpdates @ react-dom.development.js:23803
scheduleUpdateOnFiber @ react-dom.development.js:21835
dispatchAction @ react-dom.development.js:16139
(anonymous) @ InputBase.js:427
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:646
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
batchedEventUpdates$1 @ react-dom.development.js:22403
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924```

**Comment by macrozone** [comment]
i kind of remember this error, but i can't currently tell how to solve it. I think it has to do with some material-ui versions.

Maybe the material-ui version of react-page infers with that of react-admin (it looks like you are using react-admin).

I also use react-page with react-admin, so i can try to reproduce it, but i need additional information:

can you print all versions of:
- react-admin
- react-page (also check the most recent version which is 1.0.0-beta.34)
- material-ui

also check you yarn.lock or npm lock file for all material-ui versions that you are using.

**Comment by zwk5004** [comment]
> i kind of remember this error, but i can't currently tell how to solve it. I think it has to do with some material-ui versions.
> 
> Maybe the material-ui version of react-page infers with that of react-admin (it looks like you are using react-admin).
> 
> I also use react-page with react-admin, so i can try to reproduce it, but i need additional information:
> 
> can you print all versions of:
> 
> * react-admin
> * react-page (also check the most recent version which is 1.0.0-beta.34)
> * material-ui
> 
> also check you yarn.lock or npm lock file for all material-ui versions that you are using.
> 
> can you also show your `cellPlugins` array?

I don't have react admin.

react-page: 1.0.0-beta.34
material-ui: 4.11.0

**Comment by macrozone** [comment]
@zwk5004  can you show more code? where do you initialize the plugins?

**Comment by zwk5004** [comment]
`import React, { ReactElement } from "react";

import Editor, { Value } from "@react-page/editor";

import slate from "@react-page/plugins-slate";
import image from "@react-page/plugins-image";

const cellPlugins = [slate(), image];

type PageEditorProps = {
  name: string;
  editorValue: Value;
  setEditorValue: (value: Value) => void;
};

export const PageEditor = ({
  editorValue,
  setEditorValue
}: PageEditorProps): ReactElement => {
  return (
    <div style={{ color: "white", paddingBottom: 10 }}>
      <Editor
        cellPlugins={cellPlugins}
        value={editorValue}
        onChange={setEditorValue}
      />
    </div>
  );
};
`

editorValue and setEditorValue are just React.useState hook passed in as props.

**Comment by macrozone** [comment]
@zwk5004 i tried to check whether changing the value from "outside" would lead to this error, but i could not reproduce it.

i added a Reset button to the example: https://react-page.github.io/beta

at the end, you will find a reset button. It just does a `setState` to the initial value and i could not reproduce this problem.

Maybe you can setup a reproduction? I still think it has to do with material-ui as this error pops up inside material-ui

**Comment by zwk5004** [comment]
@macrozone The issue was setting the value within a clean new object each time.  Object.assign() was being used to make a clone and then the state was set to that clone.  Once I removed that cloning, everything started working as expected.  Thanks for your help on this.

**Comment by zwk5004** [comment]
@macrozone I was able to reproduce it after simplifying it down to just a button to change the value that is being used for the editor.  I added a screen recording of it happening.  `demo` and `demo2` are just pulled from the example.  Let me know if you need anything else.

https://user-images.githubusercontent.com/5647239/103497941-0fb71780-4e11-11eb-8cbd-a0c5275c9fe0.mov

**Comment by macrozone** [comment]
@zwk5004 its hard to tell without some code. can you push it to a repo?

**Comment by zwk5004** [comment]
@macrozone I created a public repo https://github.com/zwk5004/react-page-example that reproduces the issue seen in the video.

**Comment by macrozone** [comment]
@zwk5004 currently working on the reproduction. I see the error appearing on your example repo, but it does not happen if i do the same thing in the built in example

what i noticed is, that you still have `@react-page/react-page` dep, that does no longer exist. install `@react-page/editor` insteead.

But even after fixing that, it still appears. Really weird. 

keep you updated

**Comment by macrozone** [comment]
@zwk5004 ok, i found the problem. It happens when the new value has a different id.

Problem is that i did not fully remove the support for multiple editables (https://github.com/react-page/react-page/issues/873)

I think i will remove this support now as it just makes troubles

**Comment by macrozone** [comment]
@zwk5004 is fixed in 1.0.0-beta.42 !

**Comment by macrozone** [comment]
@zwk5004 by the way, do not forget to import the styles:

```

import "@react-page/editor/lib/index.css";
import "@react-page/plugins-slate/lib/index.css";
```

**Comment by macrozone** [comment]
@zwk5004 had you the chance to try it out? would love to hear your feedback!
